language: python

python:
  - "3.8"

services:
  - postgresql

env:
  - DJANGO=2.2.5 

install:
  - pip3 install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE wb;" -U postgres
  - psql -c "CREATE USER vick PASSWORD 'p';" -U postgres
  - psql -c "ALTER USER vick CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE wb to vick;" -U postgres
  - cp config/database.travis.yml config/database.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py migrate
  - python manage.py test WBBackend